name: Test Fossology Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Clone Fossology Action repository
      # Run the Fossology Action
      - name: Run Fossology Action
        id: compliance
        run: |
          chmod +x script.sh
          export REPORT_FORMAT="SPDX_JSON"
          # export GITHUB_REPOSITORY="https://github.com/EngineerMay/devsecops-github-actions-all"
          # export GITHUB_TOKEN="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"
          export SCAN_MODE="repo"  # Properly indented
          export SCANNERS="nomos ojo"
          ./script.sh
