name: Test Fossology Action
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Fossology Action
        run: |
          mkdir -p .github/actions
          git clone https://github.com/fossology/fossology-action.git .github/actions/fossology-action

      - name: Run Fossology Action
        uses: ./.github/actions/fossology-action
        with:
          scan_mode: ""
          scanners: "nomos ojo copyright keyword"
          report_format: "SPDX_JSON"
