name: Test Fossology Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Clone Fossology Action repository
      - name: Clone Fossology Action repository
        run: |
          mkdir -p .github/actions
          git clone https://github.com/fossology/fossology-action.git .github/actions/fossology-action

      # Run the Fossology Action
      - name: Run Fossology Action
        id: compliance
        run: |
          cd .github/actions/fossology-action
          export GITHUB_REPOSITORY="https://github.com/EngineerMay/devsecops-github-actions-all"
          export GITHUB_TOKEN="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"
          export SCAN_MODE="repo scans"  # Properly indented
          export SCANNERS="nomos ojo"
          ./script.sh
