name: License Compliance Scan

on:
  workflow_dispatch:

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    name: Perform license scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull public Docker image
        run: docker pull fossology/fossology

      - name: License check (placeholder)
        id: compliance
        run: |
          echo "Running license check with Fossology..."
          # Add your docker run or scanning logic here
        env:
          SCAN_MODE: ''
          SCANNERS: 'nomos ojo copyright keyword'
          REPORT_FORMAT: 'SPDX_JSON'
