on: 
  workflow_dispatch:

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    name: Perform license scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pull Fossology Docker image
      run: docker pull fossology/fossology

    - name: License check
      id: compliance
      with:
        scan_mode: ''
        scanners: 'nomos ojo copyright keyword'
        report_format: 'SPDX_JSON'
